export const SET_SEARCH_TEXT = '@videos/SET_SEARCH_TEXT';
export const CLEAR_SEARCH_TEXT = '@videos/CLEAR_SEARCH_TEXT';
export const CLEAR_SEARCH_RESULTS = '@videos/CLEAR_SEARCH_RESULTS';
export const ADD_VIDEO_FOR_LATER = '@videos/ADD_VIDEO_FOR_LATER';

export const SET_PLAYER_VIDEO_ID = '@videos/SET_PLAYER_VIDEO_ID';
export const CLEAR_PLAYER_VIDEO_ID = '@videos/CLEAR_PLAYER_VIDEO_ID';
export const SHOW_PLAYER_IFRAME = '@videos/SHOW_PLAYER_IFRAME';
export const HIDE_PLAYER_IFRAME = '@videos/HIDE_PLAYER_IFRAME';

export const SEARCH_VIDEOS_REQUEST = '@videos/SEARCH_VIDEOS_REQUEST';
export const SEARCH_VIDEOS_REQUEST_SUCCESS = '@videos/SEARCH_VIDEOS_REQUEST_SUCCESS';
export const SEARCH_VIDEOS_REQUEST_FAILURE = '@videos/SEARCH_VIDEOS_REQUEST_FAILURE';

export const RECOMMENDED_VIDEOS_REQUEST = '@videos/RECOMMENDED_VIDEOS_REQUEST';
export const RECOMMENDED_VIDEOS_REQUEST_SUCCESS = '@videos/RECOMMENDED_VIDEOS_REQUEST_SUCCESS';
export const RECOMMENDED_VIDEOS_REQUEST_FAILURE = '@videos/RECOMMENDED_VIDEOS_REQUEST_FAILURE';
