export const UPDATE_SEARCH_TEXT = '@videos/UPDATE_SEARCH_TEXT';
export const CLEAR_SEARCH_TEXT = '@videos/CLEAR_SEARCH_TEXT';
export const CLEAR_SEARCH_RESULTS = '@videos/CLEAR_SEARCH_RESULTS';
export const ADD_VIDEO_FOR_LATER = '@videos/ADD_VIDEO_FOR_LATER';

export const SEARCH_VIDEOS_REQUEST = '@videos/SEARCH_VIDEOS_REQUEST';
export const SEARCH_VIDEOS_REQUEST_SUCCESS = '@videos/SEARCH_VIDEOS_REQUEST_SUCCESS';
export const SEARCH_VIDEOS_REQUEST_FAILURE = '@videos/SEARCH_VIDEOS_REQUEST_FAILURE';